### ISSUE TITLE
InstallLombokTask should belong to group IDE

### ISSUE THREAD

**Issue by fabianMendez** [franzbecker/gradle-lombok#66]
Doing so the task can be executed from the **Gradle Tasks** view in eclipse

**Comment by franzbecker** [comment]
That was quite straightforward and I implemented it in 2.2.

However, there currently is a conceptual problem since the `installLombok` task is added to each project the plugin is applied to. If you have a multi-module project this means that if you click on the task in your IDE it will run as many times as you have modules - which is quite useless.

I will address this issue in https://github.com/franzbecker/gradle-lombok/issues/65
